/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface ConfigObject {
  /** 应当是一个完整的路径  */
  path: string
  alias: Record<string, string>
  npmPackages: Array<string>
  excludes: Array<string>
}
export function init(config: ConfigObject): void
